"""add models

Revision ID: 3c89b5b6bd0f
Revises: 
Create Date: 2021-10-28 13:14:31.635611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c89b5b6bd0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('monthlyEarnings', sa.INTEGER(), nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('Loan',
    sa.Column('loanId', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('isPaid', sa.BOOLEAN(), nullable=False),
    sa.Column('createdDate', sa.VARCHAR(length=255), nullable=False),
    sa.Column('months', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loanId')
    )
    op.create_table('Payment',
    sa.Column('paymentId', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('paidDate', sa.VARCHAR(length=255), nullable=False),
    sa.Column('loanId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['loanId'], ['Loan.loanId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paymentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payment')
    op.drop_table('Loan')
    op.drop_table('User')
    # ### end Alembic commands ###
